---
permalink: linux-administration/concept_guidelines_for_thesnapdrive_storagedisconnectcommand.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, disconnect, command, guidelines 
summary: Siga estas diretrizes ao usar o comando SnapDrive storage disconnect. 
---
= Diretrizes para o comando SnapDrive storage disconnect
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga estas diretrizes ao usar o `snapdrive storage disconnect` comando:

* Quando você desconetar um sistema de arquivos, o SnapDrive para UNIX sempre remove o ponto de montagem.
+
Os hosts Linux permitem que você anexe vários sistemas de arquivos a um único ponto de montagem. No entanto, o SnapDrive para UNIX requer um ponto de montagem exclusivo para cada sistema de arquivos. O `snapdrive storage disconnect` comando falhará se você usá-lo para desconetar sistemas de arquivos que estão conetados a um único ponto de montagem.

* Se você usar a `-lun` opção para especificar o nome de um LUN que seja membro de um grupo de discos de host ou de um sistema de arquivos, o `snapdrive storage disconnect` comando falhará.
* Se você usar `-lun` a opção para especificar o nome do LUN que não é descoberto pelo software multipathing no host, o `snapdrive storage disconnect` comando falhará.



NOTE: `snapdrive storage disconnect` O comando falha ao usar o LUN RDM, se o igrop de mapeamento tiver mais de dois nomes de porta mundial (WWPN), em versões anteriores ao SnapDrive 5,2 para UNIX.
