---
permalink: linux-administration/task_configuring_management_and_data_interfaces_for_a_storage_system.html 
sidebar: sidebar 
keywords: snap, snapdrive, management, configure, data, interface, nfs, traffic 
summary: Você pode configurar várias interfaces de dados para uma única interface de gerenciamento em um ambiente NFS, para separar o tráfego de gerenciamento do tráfego de dados no sistema de storage. 
---
= Configuração de interfaces de dados e gerenciamento para um sistema de storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar várias interfaces de dados para uma única interface de gerenciamento em um ambiente NFS, para separar o tráfego de gerenciamento do tráfego de dados no sistema de storage.

.Passos
. Defina a configuração para a nova interface de gerenciamento:
+
`*snapdrive config set root*`

+
[listing]
----
# snapdrive config set root f3050-197-91
Password for root:
Retype password:
----
+
A seguir, um exemplo para uma máquina virtual de storage (SVM, anteriormente conhecida como SVM).

+
[listing]
----
# snapdrive config set vsadmin clstr-vs2
Password for vsadmin:
Retype password:
----
. Configure a interface de dados para a nova interface de gerenciamento:
+
`*snapdrive config set*`

+
[listing]
----
# snapdrive config set -mgmtpath f3050-197-91 f3050-220-91#
----
+
No comando anterior `f3050-197-191`, é a interface de gerenciamento e `f3050-220-91` é a interface de dados.

+
Veja a seguir um exemplo para uma SVM.

+
[listing]
----
snapdrive config set -mgmtpath clstr-vs2  clstr-vs2-2
system name   management interface   datapath interface
-------------------------------------------------------
clstr-vs2     10.72.220.203          10.72.221.155
----
+
Na saída, `10.72.220.203` é a interface de gerenciamento e `10.72.221.155` é a interface de dados.


