---
permalink: linux-administration/task_viewing_the_result_of_a_clone_split_using_filespec.html 
sidebar: sidebar 
keywords: snap, snapdrive, clone, split, specification 
summary: Pode visualizar o resultado da operação de divisão de clones concluída utilizando a ID da tarefa ou a especificação do ficheiro. 
---
= Exibindo o resultado de uma operação de divisão de clones usando ID da tarefa ou especificação de arquivo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pode visualizar o resultado da operação de divisão de clones concluída utilizando a ID da tarefa ou a especificação do ficheiro.

.Passos
. Digite o seguinte comando para visualizar o resultado da divisão de clones usando uma especificação de arquivo:
+
`*snapdrive clone split result [-lun] _long_lun_name_ [_long_lun_name..._] |[{-dg | -vg | -fs | -hostvol | -lvol} _file_spec_ [_file_spec..._]] | [-job _<jobid>_]*`

+
O SnapDrive para UNIX exibe o resultado da divisão clone concluída ou falhou para uma especificação de arquivo e, em seguida, remove a especificação de arquivo da tarefa e remove a tarefa da fila de trabalhos.



O exemplo a seguir mostra o resultado da divisão de clones para um ID de tarefa que foi concluído com êxito.

[listing]
----
# snapdrive clone split result -job VT1ov6Q8vU
Clone-Split for "/mnt/my_mnt3" is 100% completed and succeeded
Clone-Split for "/mnt/my_mnt4" is 100% completed and succeeded
----
Se houver duas especificações de arquivo, e fora das quais uma das especificações de arquivo falha devido a espaço insuficiente no sistema de armazenamento, o resultado da operação de divisão de clone mostra como uma especificação de arquivo falhou e outra especificação de arquivo foi concluída com sucesso.

O exemplo a seguir mostra o resultado da divisão de clones para uma especificação de arquivo que foi concluída com sucesso.

[listing]
----
# snapdrive clone split result -fs /mnt/my_mnt3 /mnt/my_mnt4
Clone-Split for "/mnt/my_mnt3" is 100% completed and succeeded
Clone-Split for "/mnt/my_mnt4" is 100% completed and succeeded
----
O exemplo a seguir mostra o resultado da divisão de clones quando a operação de divisão de clones ainda está em andamento e ainda não foi concluída.

[listing]
----
# snapdrive clone split result -job R57aCzUaeG
Clone-Split for "/mnt/my_mnt3" is 0% completed and Split in progress
----
O exemplo a seguir mostra um trabalho que é removido permanentemente do conjunto de tarefas e, quando você tenta visualizar o resultado usando a especificação de arquivo, o SnapDrive para UNIX encontra uma mensagem de erro como "não pertence a nenhum trabalho".

[listing]
----
# snapdrive clone split result -fs /mnt/my_mnt2
Storage resource /mnt/my_mnt2 does not belong to any job
----
O exemplo a seguir mostra um trabalho que é removido permanentemente do conjunto de tarefas e, quando você tenta exibir o resultado usando ID de tarefa, o SnapDrive para UNIX encontra uma mensagem de erro como "ID de tarefa não é válido".

[listing]
----
# snapdrive clone split result -job T59aCzUaeG
Job ID is not valid
----
O exemplo a seguir exibe o resultado da divisão de clones em que uma divisão de clones está em andamento e outra falhou.

[listing]
----
# snapdrive clone split result -job qJrG8U59mg
Clone-Split for "/mnt/my_mnt4" is 100% completed and succeeded
Clone-Split for "/mnt/my_mnt5" is 0% completed and split failed
----