---
permalink: linux-administration/task_displaying_asnapshot_copy.html 
sidebar: sidebar 
keywords: snap, snapdrive, snapshot, shot, list, command 
summary: O comando SnapDrive snap show ou list exibe o nome do sistema de armazenamento onde a cópia Snapshot é criada, o nome do host, a data e a hora, etc. 
---
= Exibindo uma cópia Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O comando `snapdrive snap show` ou `list` exibe o nome do sistema de storage em que a cópia Snapshot é criada, o nome do host, a data e a hora, etc.

.Passos
. Digite a seguinte sintaxe de comando para exibir uma cópia Snapshot:
+
`*snapdrive snap show [-snapname] long_snap_name [snap_name...] [-verbose]*`



Esta operação exibe, no mínimo, as seguintes informações sobre a cópia Snapshot:

* O nome do sistema de storage em que a cópia Snapshot é criada
* O nome do host que tirou a cópia Snapshot
* O caminho para os LUNs no sistema de storage
* A data e a hora em que a cópia Snapshot foi criada
* O nome da cópia Snapshot
* Os nomes dos grupos de discos incluídos na cópia Snapshot


*Exemplo*: Os seguintes são exemplos `snapdrive snap show` de comandos:

[listing]
----
# snapdrive snap show -snapname toaster:/vol/vol2:snapA snapX snapY

# snapdrive snap show -verbose toaster:/vol/vol2:snapA /vol/vol3:snapB snapC

# snapdrive snap show toaster:/vol/vol2:snapA

# snapdrive snap list -dg dg1 dg2
----
*Exemplo*: Este exemplo usa um caractere curinga para exibir informações sobre as cópias Snapshot disponíveis em um determinado volume:

[listing]
----
# snapdrive snap show toaster:/vol/vol1:*
snap name host date
snapped
------------------------------------------------------------------
-------------
toaster:/vol/vol1:sss1 DBserver Mar 12
16:19 dg1
toaster:/vol/vol1:testdg DBserver Mar 12
15:35 dg1
toaster:/vol/vol1:t1 DBserver Mar 10
18:06 dg1
toaster:/vol/vol1:hp_1 HPserver Mar 8
19:01 vg01
toaster:/vol/vol1:r3 DBserver Mar 8
13:39 rdg1
toaster:/vol/vol1:r1 DBserver Mar 8
13:20 rdg1
toaster:/vol/vol1:snap2 DBserver Mar 8
11:51 rdg1toaster:/vol/vol1:snap_p1 DBserver
Mar 8 10:18 rdg1
----
*Exemplo*: Este exemplo mostra uma cópia Snapshot de uma árvore de diretórios montada em NFS em um host Linux usando o comando SnapDrive snap list com a `- verbose` opção:

[listing]
----
# snapdrive snap list -fs /mnt/acctfs1 -v
snap name host date
snapped
------------------------------------------------------------------
----------
besser:/vol/vol1:acctfs-s1 childs Aug 8 18:58
/mnt/acctfs1
host OS: Linux 2.4.21-9.ELsmp #1 SMP Thu Jan 8 17:08:56 EST 2004
snapshot name: acctfs-s1 file system: type: nfs mountpoint:
/mnt/acctfs1
filer dir: besser:/vol/vol1
----
*Exemplo*: Este exemplo executa o comando SnapDrive snap show em um host Linux:

[listing]
----
# snapdrive snap show -snapname surf:/vol/vol1:swzldg5snapped
snap name host date
snapped
------------------------------------------------------------------
-------------
surf:/vol/vol1:bagel5snapped pons Aug 18
20:06 dg5
#
# ./linux/ix86/snapdrive snap show -v -snapname
surf:/vol/vol1:bagel5snapped >
snap name host date
snapped
------------------------------------------------------------------
-------------
surf:/vol/vol1:bagel5snapped pons Aug 18
20:06 dg5
host OS: Linux 2.4.21-9.ELsmp #1 SMP Thu Jan 8 17:08:56 EST 2004
snapshot name: bagel5snapped
Volume Manager: linuxlvm 1.0.3
disk group: dg5
host volume: vol1
host volume: vol2
host volume: vol3
lun path dev paths
-------------------------------------------------------
surf:/vol/vol1/glk19 /dev/sdu
----
*Exemplo*: Os seguintes exemplos usam curinga:

[listing]
----
# snapdrive snap show toaster:/vol/volX:*
# snapdrive snap show -v toaster:/vol/volX:DB1*
filer1:/vol/volY:DB2*
# snapdrive snap show toaster:/vol/vol2:mysnap* /vol/vol2:yoursnap*
hersnap*
# snapdrive snap show toaster:/vol/volX:*
----
*Exemplo*: Neste exemplo, o uso de um caractere curinga é inválido porque o caractere curinga está no meio do nome em vez de ser colocado no final:

[listing]
----
# snap show toaster:/vol/vol1:my*snap
----