---
permalink: linux-administration/task_enabling_multipathing.html 
sidebar: sidebar 
keywords: snap, snapdrive, multipathing, enable, hba 
summary: Para usar multipathing no SnapDrive para UNIX, você deve concluir etapas que incluem a instalação e a inicialização do HBA. Se você estiver usando uma solução multipathing não-NetApp, você deve baixar o software e o pacote de aplicativos do site do fornecedor HBA. 
---
= Ativar multipathing
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para usar multipathing no SnapDrive para UNIX, você deve concluir etapas que incluem a instalação e a inicialização do HBA. Se você estiver usando uma solução multipathing não-NetApp, você deve baixar o software e o pacote de aplicativos do site do fornecedor HBA.

Seu sistema deve estar executando versões atuais dos componentes do sistema FC e iSCSI.

http://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"]

.Passos
. Instale os HBAs suportados antes de instalar o software Host Utilities apropriado.
+

NOTE: O SnapDrive para UNIX é compatível com HBAs de vários fornecedores.

. Inicie o serviço HBA.
+
Se o serviço HBA não estiver em execução, a seguinte mensagem de erro será exibida quando você executar comandos SnapDrive para UNIX, como `snapdrive storage create` e `snapdrive config prepare luns`:

+
[listing]
----
0001-876 Admin error: HBA assistant not found
----
+
Você deve verificar se o número necessário de caminhos está ativo e em execução. Você pode verificar os caminhos usando o `sanlun` utilitário, que está incluído no software Host Utilities. Por exemplo, na configuração de multipathing FC, você pode usar o `sanlun fcp show adapter -v` comando.

+
No exemplo a seguir, há duas portas HBA (fcd0 e fcd1) conetadas ao host que estão operacionais (estado da porta). Você pode ter apenas um iniciador HBA ou iSCSI e deve configurar multipathing fornecendo mais de um caminho para os LUNs de destino.

+
[listing]
----
# sanlun fcp show adapter -v
adapter name: fcd0
WWPN: 50060b000038c428
WWNN: 50060b000038c429
driver name: fcd
model: A6826A
model description: Fibre Channel Mass Storage Adapter
(PCI/PCI-X)
serial number: Not Available
hardware version: 3
driver version: @(#) libfcd.a HP Fibre Channel
ISP 23xx & 24xx Driver B.11.23.04
/ux/core/isu/FCD/kern/src/common/wsio/fcd_init.c:Oct 18
2005,08:19:50
firmware version: 3.3.18
Number of ports: 1 of 2
port type: Fabric
port state: Operational
supported speed: 2 GBit/sec
negotiated speed: 2 GBit/sec
OS device name: /dev/fcd0
adapter name: fcd1
WWPN: 50060b000038c42a
WWNN: 50060b000038c42b
driver name: fcd
model: A6826A
model description: Fibre Channel Mass Storage Adapter
(PCI/PCI-X)
serial number: Not Available
hardware version: 3
driver version: @(#) libfcd.a HP Fibre Channel
ISP 23xx & 24xx Driver B.11.23.04
/ux/core/isu/FCD/kern/src/common/wsio/fcd_init.c:Oct 18
2005,08:19:50
firmware version: 3.3.18
Number of ports: 2 of 2 port type: Fabric
port state: Operational
supported speed: 2 GBit/sec
negotiated speed: 2 GBit/sec
OS device name: /dev/fcd1
----
+
Se o multipathing estiver habilitado em um host, vários caminhos serão visíveis para o mesmo LUN. Você pode usar o `sanlun lun show all` comando para verificar os caminhos. No exemplo a seguir, você pode encontrar vários caminhos para o mesmo LUN (`fish: /vol/vol1/lun`):

+
[listing]
----
 [root@lnx221-75 ~]# sanlun lun show
filer:        lun-pathname device filename adapter protocol lun size lun state
f960-221-167: /vol/vol1/lun1 /dev/sdd host5 FCP 100m (104857600)      GOOD
f960-221-167: /vol/vol1/lun1 /dev/sdc host6 FCP 100m (104857600)      GOOD
----
. Se uma solução multipathing de terceiros for suportada pelo SnapDrive para UNIX ou Utilitários de host, faça o download do pacote de software de driver HBA e do pacote de aplicativos do site do fornecedor HBA.*QLogic*: Para HBAs QLogic, vá para http://support.qlogic.com/[]. Em modelos OEM, selecione NetApp. Localize a versão do driver listada na matriz de suporte e baixe-a. *Emulex:* para HBAs Emulex, vá para http://www.emulex.com/ts/index.html[]. Em Downloads, selecione NetApp. Localize a versão do driver listada na matriz de suporte e baixe-a. Baixe também o pacote Emulex Applications do mesmo local.
+
Se estiver a utilizar um adaptador QLogic com conetividade FC, transfira o script QLogic de novo digitalização a partir do Web site do QLogic e copie-o para `/root` o caminho (por exemplo, `/root/dynamic-lun-rescan.sh` ). O script de redigitalização do QLogic pede confirmação do usuário; o SnapDrive para UNIX pode travar indefinidamente nesta fase de confirmação. Você pode evitar essa confirmação definindo a variável `_QL_DISABLE_WARNING_` como `1` no script.

+
Versões anteriores do SnapDrive para UNIX usavam scripts SCSI de revenda específicos do fornecedor para verificar LUNs pelo FC e, assim, copiar scripts específicos do fornecedor para `/root/dynamic-lun-rescan.sh`o . Isso foi disponibilizado até RHEL 5U3.

+
Para RHEL 5U4/ SLES 10SP2 e versões posteriores, o script de redigitalização está atualmente disponível `/usr/bin` no diretório. Caso o script de redigitalização não esteja disponível no diretório, ele está presente junto com o `sg3_utils` pacote.

+

NOTE: Você deve garantir que as `sg3_utils` bibliotecas e `sg3_utils-libs` estejam disponíveis para as versões Red Hat Enterprise Linux (RHEL) e Oracle Enterprise Linux (OEL). No entanto, as `sg3_utils` bibliotecas estão disponíveis para a versão do SUSE Linux Enterprise Server (SLES) no `scsci utility.rpm` pacote.

. Em uma configuração FC, zoneie as portas HBA do host e as portas de destino usando a configuração de zoneamento do switch.
. Instale e configure o switch FC apropriado.
. Verifique os requisitos de pilha do SnapDrive para UNIX.
. Instale ou atualize o SnapDrive para UNIX.
. Verifique a instalação do SnapDrive para UNIX.
. Localize o `snapdrive.conf` caminho do arquivo.
. Configure as seguintes variáveis de configuração `snapdrive.conf` no arquivo:
+
** `_multipathing-type_`
** `_default-transport_`
** `_fstype_`
** `_vmtype_`
+
Para cada host, o tipo de multipathing, o tipo de transporte, o sistema de arquivos e o tipo de gerenciador de volume dependem um do outro. A tabela a seguir descreve todas as combinações possíveis:

+
|===
| Plataforma host | Tipo de transporte predefinido | Tipo de multipathing | fstype | vmtype 


 a| 
Linux
 a| 
iscsi
 a| 
nativempio
 a| 
ext4 ou ext3
 a| 
lvm



 a| 
iscsi
 a| 
nenhum
 a| 
ext4 ou ext3
 a| 
lvm



 a| 
FCP
 a| 
nenhum
 a| 
ext4 ou ext3
 a| 
lvm



 a| 
FCP
 a| 
nativempio
 a| 
ext4 ou ext3
 a| 
lvm

|===
+
A tabela anterior fornece os valores suportados das `_multipathing-type_` variáveis de configuração , `_default-transport_`, `_fstype_` e . `_vmtype_`

+

NOTE: Se o protocolo de transporte for `iSCSI`, e o tipo de multipathing estiver definido como `none`, você deverá parar o daemon multipath e executar comandos SnapDrive for UNIX.



. Salve o `snapdrive.conf` arquivo.
+
O SnapDrive para UNIX verifica automaticamente esse arquivo sempre que ele for iniciado. Você deve reiniciar o daemon SnapDrive para UNIX para que as alterações entrem em vigor.



*Informações relacionadas*

xref:concept_snaprestore_and_snapconnect_operations_do_not_work_in_linux_after_multipathing_migration.adoc[As operações SnapRestore e Snapconnect não funcionam no Linux após a migração do tipo multipathing]

http://mysupport.netapp.com["Suporte à NetApp"]

https://mysupport.netapp.com/NOW/products/interoperability["Interoperabilidade do NetApp"]

https://library.netapp.com/ecm/ecm_download_file/ECMLP2547936["Guia de instalação do Linux Unified Host Utilities 7,1"]
