---
permalink: aix/concept_example_of_an_autosupport_message.html 
sidebar: sidebar 
keywords: snap, snapdrive, example, autosupport, message, support 
summary: O SnapDrive para UNIX fornece exemplos para diferentes cenários. O conteúdo de uma mensagem do AutoSupport em todos os exemplos é essencialmente o mesmo, independentemente do seu sistema operacional. 
---
= Exemplos de mensagens AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapDrive para UNIX fornece exemplos para diferentes cenários. O conteúdo de uma mensagem do AutoSupport em todos os exemplos é essencialmente o mesmo, independentemente do seu sistema operacional.

Exemplo: Adicionando um novo sistema de armazenamento

O exemplo a seguir é uma mensagem enviada de um host `_aix207-116_` chamado :

[listing]
----
computerName="aix207-116"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="3"
        category="ohio configured"
        subject="host_name=aix207-116, host_os=AIX, host_os_release=1, host_os_version=6, No of controller=1, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=No, Protocol=fcp"
----
Exemplo: Reiniciando o Daemon

O SnapDrive para UNIX envia a seguinte mensagem AutoSupport para o sistema de armazenamento quando você reinicia o daemon:

[listing]
----
computerName="aix207-116"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="2"
        category="daemon restarted"
        subject="host_name=aix207-116, host_os=AIX, host_os_release=1, host_os_version=6, No of controller=1, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=No, Protocol=fcp"
----
O SnapDrive para UNIX envia a seguinte mensagem AutoSupport ao sistema de storage quando uma operação de conexão de storage falha:

[listing]
----
computerName="aix207-116"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="4"
        category="storage connect failed"
        subject="host_name=aix207-116, host_os=AIX, host_os_release=1, host_os_version=6, No of controller=1, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=No, Protocol=fcp,1384: LUN /vol/vol0/test1 on storage system ohio already mapped to initiators in igroup aix207-116_fcp_SdIg at ID 0."/
----
O SnapDrive para UNIX envia a seguinte mensagem AutoSupport ao sistema de storage quando uma `snap create` operação é bem-sucedida:

[listing]
----
computerName="aix207-116"
        eventSource="snapdrive"
        appVersion="5.2 for UNIX"
        eventID="5"
        category="snap create successful"
        subject="host_name=aix207-116, host_os=AIX, host_os_release=1, host_os_version=6, No of controller=1, PM/RBAC=native, Host Virtualization=No, Multipath-type=nativempio, Protection Enabled=No, Protocol=fcp, snapshot_name=snap1"
----