---
permalink: aix/task_configuring_user_credentials_on_snapdrive_for_unix.html 
sidebar: sidebar 
keywords: snap, snapdrive, user, credentials, operations, manager, console, configure 
summary: O administrador do SnapDrive para UNIX recebe credenciais de usuário do administrador do console do Gerenciador de operações. Essas credenciais de usuário precisam ser configuradas no SnapDrive para UNIX para operações de storage adequadas. 
---
= Configurando credenciais de usuário no SnapDrive para UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O administrador do SnapDrive para UNIX recebe credenciais de usuário do administrador do console do Gerenciador de operações. Essas credenciais de usuário precisam ser configuradas no SnapDrive para UNIX para operações de storage adequadas.

.Passos
. Configure o SD-admin no sistema de armazenamento.
+
[listing]
----
[root]#snapdrive config set -dfm sd-admin ops_mngr_server
Password for sd-admin:
Retype password:
----
. Configure o SD-hostname no sistema de armazenamento.
+
[listing]
----
[root]#snapdrive config set sd-unix_host storage_array1
Password for sd-unix_host:
Retype password:
----
. Verifique as etapas 1 e 2, usando o `snapdrive config list` comando.
+
[listing]
----
user name       appliance name          appliance type
----------------------------------------------------
sd-admin        ops_mngr_server         DFM
sd-unix_host    storage_array1          StorageSystem
----
. Configure o SnapDrive para UNIX para usar o controle de acesso baseado em função (RBAC) do console do Gerenciador de operações definindo a variável de `rbac-method="dfm"` configuração no `snapdrive.conf` arquivo.
+

NOTE: As credenciais do usuário são criptografadas e salvas no arquivo existente `.sdupw`. O local padrão do arquivo anterior é `/opt/NetApp/snapdrive/.sdupw`.


