---
permalink: aix/task_creating_a_filesystem_on_a_lunand_setting_up_thelun_automatically.html 
sidebar: sidebar 
keywords: snap, snapdrive, lun, file, system, create 
summary: Você pode criar um sistema de arquivos em um LUN usando o SnapDrive para UNIX. O SnapDrive para UNIX cria automaticamente o LUN associado. 
---
= Criando um sistema de arquivos em um LUN e configurando o LUN automaticamente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode criar um sistema de arquivos em um LUN usando o SnapDrive para UNIX. O SnapDrive para UNIX cria automaticamente o LUN associado.

.Passos
. Na linha de comando, digite o seguinte comando:
+
`*snapdrive storage create -fs _file_spec_ -nolvm [-fstype type] [-fsopts options] [-mntopts options] [-nopersist] -filervol _long_filer_path_ -lunsize _size_ [-igroup _ig_name [ig_name ...]]_ [{-reserve | -noreserve }]*`

+
O SnapDrive para UNIX cria o sistema de arquivos especificado e cria um LUN para ele no sistema de storage especificado. Ele executa todas as tarefas associadas à preparação e descoberta do host para os LUNs, bem como mapeando e conetando os LUNs à entidade do host.





== Exemplos:

*Criando um sistema de arquivos de 100 MB diretamente em um LUN:*

[listing]
----
# snapdrive storage create -fs /mnt/acct1 -filervol acctfiler:/vol/vol1 -lunsize 100m -nolvm
----
*Criando um sistema de arquivos em um LUN bruto sem qualquer gerenciador de volume:*

[listing]
----
# snapdrive storage create -fs /mnt/vxfs2 -fstype vxfs -lun
snoopy:/vol/vol1/lunVxvm2 -lunsize 50m -nolvm
LUN snoopy:/vol/vol1/lunVxvm2 ... created
mapping new lun(s) ... done
discovering new lun(s) ... done
LUN to device file mappings:
- snoopy:/vol/vol1/lunVxvm2 => /dev/vx/dmp/Disk_1
file system /mnt/vxfs2 created
----