---
permalink: aix/task_installing_snapdrive_for_unix_on_an_aix_host.html 
sidebar: sidebar 
keywords: snap, snapdrive, install, aix, host, unix 
summary: 'Você pode usar a ferramenta de interface de gerenciamento do sistema (SMIT) para instalar o SnapDrive para UNIX no host AIX.' 
---
= Instalando o SnapDrive para UNIX em um host AIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar a ferramenta de interface de gerenciamento do sistema (SMIT) para instalar o SnapDrive para UNIX no host AIX.

Você deve garantir que você está conetado como um usuário root.


IMPORTANT: Você não deve excluir o diretório onde o SnapDrive para UNIX está instalado. Se você excluir o diretório, pode haver problemas ao iniciar e parar o daemon.

.Passos
. Transfira o software a partir do site de suporte da NetApp.
. Mude para o diretório no qual você colocou o descompactado . `NetApp.snapdrive_aix_5_2.z file`
. Inicie O SMIT executando o seguinte comando:
+
`*smit*`

. Selecione a opção *Instalação e Manutenção de Software*.
. Na tela seguinte, selecione a opção de menu *Instalar e Atualizar Software*.
. Na tela Instalar software, especifique a localização do software de uma das seguintes maneiras:
+
** Introduza manualmente o caminho da localização do software.
** Pressione F4 para exibir uma lista de opções.


+
Se você quiser usar o método F4, execute as seguintes etapas:

+
.. Pressione F4.
.. No prompt perguntando qual software você deseja instalar, digite:
+
`*NetApp.snapdrive*`.

.. No prompt perguntando se deseja continuar ou cancelar, pressione Enter para concluir a instalação.


. Verifique a instalação do pacote de software usando o `lslpp -l NetApp.snapdrive` comando.
. Conclua a configuração configurando o SnapDrive para UNIX para o sistema.
+
A maioria dessas informações é definida por padrão; no entanto, você precisa especificar as seguintes informações:

+
.. Informações de login para o sistema de armazenamento
.. Definições AutoSupport
.. Defina o valor de configuração correto para as seguintes opções,SnapDrive para UNIX com base se está a utilizar o protocolo FC ou o protocolo iSCSI:
+
*** `default-transport`
+
 `FCP`Selecione ou `iscsi`, dependendo do protocolo.

*** `multipathing-type`
+
Para FC, defina-o para qualquer um dos seguintes valores:

+
**** `NativeMPIO`
**** `DMP`






+
Para iSCSI, defina como `NativeMPIO` ou `DMP`.


