---
permalink: solaris/concept_what_the_web_service_and_daemon_are.html 
sidebar: sidebar 
keywords: snap, snapdrive, web, service, daemon 
summary: O serviço Web SnapDrive para UNIX fornece uma interface uniforme para todos os NetApp SnapManager e produtos de terceiros para se integrarem perfeitamente com o SnapDrive para UNIX. Para usar comandos de interface de linha de comando no SnapDrive para UNIX, você precisa iniciar o daemon. 
---
= O que são o serviço Web e o daemon
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O serviço Web SnapDrive para UNIX fornece uma interface uniforme para todos os NetApp SnapManager e produtos de terceiros para se integrarem perfeitamente com o SnapDrive para UNIX. Para usar comandos de interface de linha de comando (CLI) no SnapDrive para UNIX, você precisa iniciar o daemon.

Vários produtos NetApp SnapManager usam a interface de linha de comando (CLI) para se comunicar com o SnapDrive para UNIX. O uso da CLI coloca uma restrição no desempenho e gerenciabilidade do SnapManager e do SnapDrive para UNIX. Quando você usa o daemon SnapDrive para UNIX, todos os comandos funcionam como um processo exclusivo. O serviço Daemon não afeta a maneira como os comandos SnapDrive para UNIX são usados.

O serviço Web SnapDrive para UNIX permite que aplicativos de terceiros se integrem perfeitamente com o SnapDrive para UNIX. Eles interagem com o SnapDrive para UNIX usando APIs.

Quando você inicia o daemon, o SnapDrive para UNIX primeiro verifica se o daemon está sendo executado. Se o daemon não estiver em execução, ele iniciará o daemon. Se o daemon já estiver em execução e você tentar iniciá-lo, o SnapDrive para UNIX exibirá a mensagem:

`snapdrive daemon is already running`

Você pode verificar o status do daemon para ver se o SnapDrive para UNIX está em execução ou não. Você deve verificar o status antes de decidir iniciar o daemon. Se um usuário que não seja o usuário raiz tentar verificar o status, o SnapDrive para UNIX verifica as credenciais do usuário e exibe a mensagem:

`snapdrive daemon status can be seen only by root user`

Quando você tenta parar o daemon, o SnapDrive para UNIX verifica suas credenciais. Se você for um usuário diferente do usuário raiz, o SnapDrive para UNIX exibirá a mensagem

`snapdrive daemon can be stopped only by root user`

Depois de parar o daemon, você deve reiniciar o daemon SnapDrive para UNIX para que quaisquer alterações no arquivo de configuração ou em qualquer módulo entrem em vigor. Se um usuário que não seja o usuário raiz tentar reiniciar o daemon SnapDrive para UNIX, o SnapDrive para UNIX verifica as credenciais do usuário e exibe a mensagem

`snapdrive daemon can be restarted only by root user`
