---
permalink: solaris/concept_guidelines_for_snapshot_copy_creation_in_a_host_cluster_environment.html 
sidebar: sidebar 
keywords: snap, snapdrive, snapshot, copy, create, host, cluster 
summary: A criação de cópias Snapshot com o SnapDrive para UNIX é compatível em algum ambiente, mas não em alguns. Consulte as diretrizes para saber mais. 
---
= Diretrizes para a criação de cópias Snapshot em um ambiente de cluster de host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A criação de cópias Snapshot com o SnapDrive para UNIX é compatível em algum ambiente, mas não em alguns. Consulte as diretrizes para saber mais.

* O SnapDrive para UNIX pode criar cópias Snapshot de grupos de discos e sistemas de arquivos compartilhados com um parceiro de cluster de host no ambiente Veritas SFRAC 4,1.
* A operação Snapshot Create pode ser invocada a partir de qualquer nó no cluster de host.
* Os vários sistemas de arquivos e grupos de discos especificados nesta operação devem ter o mesmo escopo: Ou seja, todos devem ser compartilhados ou todos devem ser dedicados.
* Um sistema de arquivos NFS no modo compartilhado em todo o cluster não é compatível, mas um sistema de arquivos NFS no modo dedicado em nós de cluster de host é compatível.
* Sistemas de arquivos não são compatíveis com LUNs brutos.

