---
permalink: solaris/concept_storage_provisioning_for_rdm_luns.html 
sidebar: sidebar 
keywords: snap, snapdrive, vmware, vmotion, support, unix 
summary: O SnapDrive para UNIX permite que você desconete e conete os LUNs RDM antes e depois do VMware VMotion. Após a conclusão da operação do VMotion, você pode executar as operações de storage necessárias para o seu sistema de storage. 
---
= Suporte ao VMware VMotion no SnapDrive para UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapDrive para UNIX permite que você desconete e conete os LUNs RDM antes e depois do VMware VMotion. Após a conclusão da operação do VMotion, você pode executar as operações de storage necessárias para o seu sistema de storage.

*Sobre o VMware VMotion:*

O VMware VMotion permite que você mova um sistema convidado de um servidor ESX para outro servidor ESX.

As operações a seguir devem ser executadas para desconetar e conetar os LUNs RDM no SnapDrive para UNIX.

*Antes do VMotion*

Você precisa usar o `snapdrive storage disconnect` comando para remover os mapeamentos dos LUNs RDM. A seguinte sintaxe:

`*snapdrive storage disconnect -lun _long_lun_name_ [_lun_name..._]*`

*Depois do VMotion*

Depois que o VMotion estiver concluído, você deve usar o `snapdrive storage connect` comando para conetar LUNs RDM. A seguinte sintaxe:

`*snapdrive storage connect -lun _long_lun_name_ [_lun_name..._]*`

*Informações relacionadas*

xref:concept_limitations_of_rdm_luns_managed_by_snapdrive.adoc[Limitações de LUNs RDM gerenciados pelo SnapDrive]

xref:task_configuring_virtual_storage_console_in_snapdrive_for_unix.adoc[Configurando o console de storage virtual para SnapDrive para UNIX]

xref:concept_guest_os_preparation_for_installing_sdu.adoc[Preparação do SO convidado para instalar o SnapDrive para UNIX]

xref:task_considerations_for_provisioning_rdm_luns.adoc[Considerações para provisionar LUNs RDM]
