---
permalink: solaris/concept_support_for_guest_operating_systems.html 
sidebar: sidebar 
keywords: snap, snapdrive, support, guest, operating, system 
summary: 'O suporte do SnapDrive para UNIX para sistemas operacionais convidados permite criar storage e gerenciar cópias Snapshot de LUNs, sistemas de arquivos, volumes lógicos e grupos de discos. Para provisionar LUNs RDM, você precisa especificar o protocolo Fibre channel (FC) no arquivo SnapDrive.conf.' 
---
= Suporte para sistemas operacionais convidados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O suporte do SnapDrive para UNIX para sistemas operacionais convidados permite criar storage e gerenciar cópias Snapshot de LUNs, sistemas de arquivos, volumes lógicos e grupos de discos. Para provisionar LUNs RDM, você precisa especificar o protocolo Fibre Channel (FC) no arquivo SnapDrive.conf.

* Crie um armazenamento que inclua LUNs, LUNs RDM, sistemas de arquivos, volumes lógicos e grupos de discos.
+
Depois de criar o armazenamento, você pode aumentar ou reduzir a capacidade de armazenamento, conetar o armazenamento a um host ou desconetar e exibir informações de configuração sobre o armazenamento.

* Crie uma cópia Snapshot de um ou mais grupos de volumes em um sistema de storage.
+
A cópia Snapshot pode conter sistemas de arquivos, volumes lógicos, grupos de discos, LUNs, LUNs RDM LUNs e árvores de diretório NFS. Depois de criar uma cópia Snapshot, você pode renomear, restaurar ou excluir a cópia Snapshot. Você também pode conetar uma cópia Snapshot a um local diferente no mesmo host ou diferente. Depois de conetar a cópia Snapshot, você pode exibir e modificar o conteúdo ou desconetar. Você também pode exibir informações sobre as cópias Snapshot.


