---
permalink: solaris/concept_disconnecting_a_filespec.html 
sidebar: sidebar 
keywords: snap, snapdrive, disconnect, filespec 
summary: Você pode desconetar uma especificação de arquivo. O exemplo a seguir descreve como você pode concluir esta operação. 
---
= Desligar uma especificação de ficheiro
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode desconetar uma especificação de arquivo. O exemplo a seguir descreve como você pode concluir esta operação.

O layout do `/mnt/fs1_0` é dado no seguinte.

[listing]
----
# snapdrive storage show -fs /mnt/fs_1_0 -capabilities
raw device: /dev/sde1   mount point: /mnt/fs_1_0 (persistent) fstype ufs
allowed operations: all

device filename    adapter  path    size    proto   state   clone         lun path                                                         backing snapshot
----------------   -------  ----    ----    -----   -----   -----         --------                                                         ----------------
/dev/sde              -      P      100m    iscsi   online  flex-clone    homer:/vol/Snapdrive_vol1_volume_clone_from_snap2_snapshot/lun1    vol1:snap2
----
A saída a seguir mostra como desconetar o sistema de arquivos `/mnt/fs_1_0` :

[listing]
----
#snapdrive snap disconnect -fs /mnt/fs_1_0
 delete file system /mnt/fs_1_0
- fs /mnt/fs_1_0 ... deleted
         - LUN homer:/vol/Snapdrive_vol1_volume_clone_from_snap2_snapshot/lun1 ... disconnected
         - deleting volume clone ... homer:/vol/Snapdrive_vol1_volume_clone_from_snap2_snapshot  done
----
Depois de desconetar o sistema de arquivos `/mnt/fs_1_0` , o SnapDrive para UNIX também exclui o volume clonado , `Snapdrive_vol1_0_volume_clone_from_snap2_snapshot`se as seguintes condições forem atendidas:

* Não há LUNs mapeados presentes no volume
* Não há novos LUNs presentes
* Nenhuma nova cópia Snapshot está presente


*Excluindo um FlexClone não criado pelo SnapDrive para UNIX*: O SnapDrive para UNIX não permite a exclusão do FlexClone não criado por ele.
