---
permalink: solaris/task_estimating_the_storage_space_to_split_a_lun_clone.html 
sidebar: sidebar 
keywords: snap, snapdrive, estimate, storage, split, lun, clone 
summary: 'A estimativa de divisão de clones ajuda você a estimar o espaço de armazenamento necessário (em MB) para dividir um clone de LUN. Dependendo da estimativa de divisão de clones fornecida pelo SnapDrive para UNIX, é possível determinar a disponibilidade de espaço para dividir um clone de LUN.' 
---
= Estimando o espaço de armazenamento para dividir um clone de LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A estimativa de divisão de clones ajuda você a estimar o espaço de armazenamento necessário (em MB) para dividir um clone de LUN. Dependendo da estimativa de divisão de clones fornecida pelo SnapDrive para UNIX, é possível determinar a disponibilidade de espaço para dividir um clone de LUN.

.Passos
. Digite o seguinte comando para estimar o espaço de armazenamento necessário para dividir um clone de LUN.
+
`*snapdrive clone split estimate [-lun] _long_lun_name_ [_long_lun_name..._] | [{-dg | -vg | -fs | -hostvol | -lvol}_file_spec_ [_file_spec..._]] | [-snapname _long_snap_name_] {-volclone|-lunclone}] [-v | -verbose]*`

+
Esta operação apresenta as seguintes informações:

+
** Nome do recurso
** Contêiner- volume para um clone de LUN
** Espaço necessário - espaço necessário para dividir um clone de LUN
** Espaço disponível - espaço disponível no recipiente
** Estado de armazenamento - indica a disponibilidade de espaço para um divisão de clone LUN
** Espaço de propriedade - espaço ocupado pelo clone LUN
** Espaço compartilhado - espaço ocupado pelo clone LUN junto com o pai


+
O `Owned Space` e `Shared Space` é apresentado quando utiliza `-verbose` a opção.



O exemplo a seguir estima o espaço de storage para dividir um clone de LUN.

[listing]
----
# snapdrive clone split estimate -fs /mnt/my_mnt1
Resource     Container Required Available Storage
                       Space(MB)Space(MB) Status
/mnt/my_mnt1 f3050-220  5120    9986    AVAILABLE
             -112:/vol/vol_1
----
O seguinte é um exemplo de uso da `-verbose` opção. Alternativamente, você pode usar `-v` a opção.

[listing]
----
# snapdrive clone split estimate -fs /mnt/my_mnt1 -verbose
Resource    Container  Owned    Shared   Required Available Storage
                       Space(MB)Space(MB)Space(MB)Space(MB) Status
/mnt/my_mnt1 f3050-220  365   403      5120     9986 AVAILABLE
             -112:/vol/vol_1
----