---
permalink: solaris/task_displaying_asnapshot_copy.html 
sidebar: sidebar 
keywords: snap, snapdrive, display, snapshot, copy 
summary: O comando SnapDrive snap show ou list exibe o nome do sistema de armazenamento onde a cópia Snapshot é criada, o nome do host, a data e a hora, etc. 
---
= Exibindo uma cópia Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O comando `snapdrive snap show` ou `list` exibe o nome do sistema de storage em que a cópia Snapshot é criada, o nome do host, a data e a hora, etc.

.Passos
. Digite a seguinte sintaxe de comando para exibir uma cópia Snapshot:
+
`*snapdrive snap show [-snapname] _long_snap_name_ [_snap_name_...] [-verbose]*`



Esta operação exibe, no mínimo, as seguintes informações sobre a cópia Snapshot:

* O nome do sistema de storage em que a cópia Snapshot é criada
* O nome do host que tirou a cópia Snapshot
* O caminho para os LUNs no sistema de storage
* A data e a hora em que a cópia Snapshot foi criada
* O nome da cópia Snapshot
* Os nomes dos grupos de discos incluídos na cópia Snapshot


*Exemplo*: Os seguintes são exemplos `snapdrive snap show` de comandos:

[listing]
----
# snapdrive snap show -snapname toaster:/vol/vol2:snapA snapX snapY

# snapdrive snap show -verbose toaster:/vol/vol2:snapA /vol/vol3:snapB snapC

# snapdrive snap show toaster:/vol/vol2:snapA

# snapdrive snap list -dg dg1 dg2
----
*Exemplo*: Este exemplo usa um caractere curinga para exibir informações sobre as cópias Snapshot disponíveis em um determinado volume:

[listing]
----
# snapdrive snap show toaster:/vol/vol1:*
snap name host date
snapped
------------------------------------------------------------------
-------------
toaster:/vol/vol1:sss1 DBserver Mar 12
16:19 dg1
toaster:/vol/vol1:testdg DBserver Mar 12
15:35 dg1
toaster:/vol/vol1:t1 DBserver Mar 10
18:06 dg1
toaster:/vol/vol1:hp_1 HPserver Mar 8
19:01 vg01
toaster:/vol/vol1:r3 DBserver Mar 8
13:39 rdg1
toaster:/vol/vol1:r1 DBserver Mar 8
13:20 rdg1
toaster:/vol/vol1:snap2 DBserver Mar 8
11:51 rdg1toaster:/vol/vol1:snap_p1 DBserver
Mar 8 10:18 rdg1
----
*Exemplo*: Os seguintes exemplos usam curinga:

[listing]
----
# snapdrive snap show toaster:/vol/volX:*
# snapdrive snap show -v toaster:/vol/volX:DB1*
filer1:/vol/volY:DB2*
# snapdrive snap show toaster:/vol/vol2:mysnap* /vol/vol2:yoursnap*
hersnap*
# snapdrive snap show toaster:/vol/volX:*
----
*Exemplo*: Neste exemplo, o uso de um caractere curinga é inválido porque o caractere curinga está no meio do nome em vez de ser colocado no final:

[listing]
----
# snap show toaster:/vol/vol1:my*snap
----